"""Command-line interface for TranscribeBench."""

from __future__ import annotations

import argparse
import sys

from .config import Config
from .engines import MlxWhisperEngine, FasterWhisperEngine, WhisperCppEngine
from .runner import BenchmarkRunner


def _build_engines(config: Config):
    mapping = {
        "mlx_whisper": MlxWhisperEngine(),
        "faster_whisper": FasterWhisperEngine("faster_whisper"),
        "faster_whisper_large": FasterWhisperEngine("faster_whisper_large"),
        "whisper_cpp": WhisperCppEngine(),
    }

    enabled = []
    if config.engines.mlx_whisper.enabled:
        enabled.append("mlx_whisper")
    if config.engines.faster_whisper.enabled:
        enabled.append("faster_whisper")
    if config.engines.faster_whisper_large.enabled:
        enabled.append("faster_whisper_large")
    if config.engines.whisper_cpp.enabled:
        enabled.append("whisper_cpp")

    return [mapping[name] for name in enabled if name in mapping]


def _cmd_setup(args: argparse.Namespace) -> int:
    config = Config.load(args.config)
    engines = _build_engines(config)

    messages = []
    for engine in engines:
        missing = engine.check_requirements()
        if missing:
            messages.append(f"Engine {engine.name} requirements:")
            messages.extend([f"  - {m}" for m in missing])

    if messages:
        print("Setup checks completed with messages:")
        print("\n".join(messages))
        return 1

    print("All known requirements appear satisfied.")
    return 0


def _cmd_fetch_dataset(args: argparse.Namespace) -> int:
    config = Config.load(args.config)
    runner = BenchmarkRunner(config, [])
    runner.dataset_provider.fetch(
        language=config.language,
        size=config.dataset.sample_size,
        seed=config.dataset.seed,
        url=config.dataset.url,
    )
    print("Dataset fetched (or already cached).")
    return 0


def _cmd_run_benchmark(args: argparse.Namespace) -> int:
    config = Config.load(args.config)
    engines = _build_engines(config)

    usable_engines = []
    for engine in engines:
        missing = engine.check_requirements()
        if missing:
            print(f"Skipping engine {engine.name}: missing requirements:")
            for m in missing:
                print(f"  - {m}")
        else:
            usable_engines.append(engine)

    if not usable_engines:
        print("No usable engines available; please install dependencies or enable a supported engine.")
        return 1

    runner = BenchmarkRunner(config, usable_engines)
    results = runner.run()
    runner.save_results(results)
    print(f"Benchmark complete. Results written to: {config.output.results_dir}")
    return 0


def _cmd_report(args: argparse.Namespace) -> int:
    config = Config.load(args.config)
    from pathlib import Path

    out_dir = Path(config.output.reports_dir)
    if not out_dir.exists():
        print(f"Report directory does not exist: {out_dir}")
        return 1

    # In this version, report is generated by saving results (no-op if already present)
    print(f"Report artifacts are in: {out_dir}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="transcribebench")
    parser.add_argument("--config", default="config.yaml", help="Path to config file")

    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("setup", help="Check prerequisites for enabled engines")
    subparsers.add_parser("fetch-dataset", help="Download/cache dataset subset")
    subparsers.add_parser("run-benchmark", help="Run the benchmark and store results")
    subparsers.add_parser("report", help="Generate human-readable report artifacts")

    args = parser.parse_args(argv)

    if args.command == "setup":
        return _cmd_setup(args)
    if args.command == "fetch-dataset":
        return _cmd_fetch_dataset(args)
    if args.command == "run-benchmark":
        return _cmd_run_benchmark(args)
    if args.command == "report":
        return _cmd_report(args)

    parser.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
